### ISSUE TITLE
Add option to Skip SSL Validation when performing Universal Package Publish

### ISSUE THREAD

**Issue by ahaleiii** [Microsoft/azure-devops-cli-extension#232]
I tried running the `vsts package universal publish` command for the first time, but was unable to complete the operation do to a failure to validate SSL certificates:

`certificate verify failed: self signed certificate in certificate chain`

I do not have access to my organization's certs so I cannot perform the environment variable workaround mentioned in #76. Is there a way that I can bypass ssl validation so that I can publish my universal package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052cdfe9-bd19-bf90-d63e-91e5d7e2f3e9
* Version Independent ID: 2ae25fe6-634d-8623-9f14-1b48b646bd27
* Content: [vsts package universal](https://docs.microsoft.com/en-us/cli/vsts/package/universal?view=vsts-cli-latest#vsts-package-universal-publish)
* Content Source: [src/command_modules/vsts-cli-package/vsts/cli/package/_help.py](https://github.com/Microsoft/vsts-cli/blob/master/src/command_modules/vsts-cli-package/vsts/cli/package/_help.py)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ahaleiii** [comment]
Full de-identified debug logs:
```
PS D:\nuget_publish\appdynamics_universalpackage> vsts package universal publish --feed MyFeed --name appdynamics-dotnet-core --version 1.0.0-beta.1539990418 --description "Initial version of AppDynamics agent files, including a tokenized config file." --path . --debug
Command arguments: ['package', 'universal', 'publish', '--feed', 'MyFeed', '--name', 'appdynamics-dotnet-core', '--version', '1.0.0-beta.1539990418', '--description', 'Initial version of AppDynamics agent files, including a tokenized config file.', '--path', '.', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0439BE40>, <function OutputProducer.on_global_arguments at 0x043CCA08>, <function CLIQuery.on_global_arguments at 0x045B03D8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x0439BE88>]
Event: CommandLoader.OnLoadCommandTable []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x043CCA50>, <function CLIQuery.handle_query_parameter at 0x045B0420>, <function VstsCLI.post_parse_args at 0x04E42270>]
Universal Packages is currently in preview.
GitDetect: Could not detect current remotes based on current working directory.
Command '['git', 'remote', '-v']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\common\git.py", line 100, in get_git_remotes
    output = subprocess.check_output([_GIT_EXE, 'remote', '-v'], stderr=subprocess.STDOUT)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'remote', '-v']' returned non-zero exit status 128.
Detect: Url discovery took 0:00:00.082063
Checking for a new ArtifactTool
Checking for ArtifactTool updates
Getting credential: vsts-cli:https://dev.azure.com
Creating connection with personal access token.
Telemetry enabled.
vsts._file_cache : Loading cache file: C:\Users\myuser\.vsts\python-sdk\cache\options.json
vsts._file_cache : attempting to read file C:\Users\myuser\.vsts\python-sdk\cache\options.json as utf-8-sig
vsts.vss_client : File cache hit for options on: https://dev.azure.com/myorg
vsts.vss_client : Route template: _apis/{area}/{resource}
vsts.vss_client : Api version '4.0-preview.1'
vsts._file_cache : Loading cache file: C:\Users\myuser\.vsts\python-sdk\cache\resources.json
vsts.vss_client : POST https://dev.azure.com/myorg/_apis/CustomerIntelligence/Events
vsts._file_cache : attempting to read file C:\Users\myuser\.vsts\python-sdk\cache\resources.json as utf-8-sig
vsts.vss_client : Request content: [{'area': 'CLI', 'feature': 'package', 'properties': {'Command': 'universal publish', 'Args': ['feed', 'name', 'version', 'description', 'path']}}]
vsts.vss_connection : File cache hit for resources on: https://dev.azure.com/myorg
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=NoneLooking up current version of ArtifactTool...

vsts.vss_client : File cache miss for options on: https://myorg.vsblob.visualstudio.com
msrest.pipeline : Configuring proxies: ''
vsts.vss_client : OPTIONS https://myorg.vsblob.visualstudio.com/_apis
msrest.pipeline : Evaluate proxies against ENV settings: True
vsts.vss_client : Request content: None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.pipeline : Configuring proxies: ''
urllib3.connectionpool : Starting new HTTPS connection (1): dev.azure.com:443
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): myorg.vsblob.visualstudio.com:443
urllib3.util.retry : Incremented Retry for (url='/_apis'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /_apis
urllib3.connectionpool : Starting new HTTPS connection (2): myorg.vsblob.visualstudio.com:443
urllib3.util.retry : Incremented Retry for (url='/_apis'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : https://dev.azure.com:443 "POST /myorg/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
vsts.vss_client : Response content: b''
urllib3.connectionpool : Retrying (Retry(total=1, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /_apis
urllib3.connectionpool : Starting new HTTPS connection (3): myorg.vsblob.visualstudio.com:443
urllib3.util.retry : Incremented Retry for (url='/_apis'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=0, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'))': /_apis
urllib3.connectionpool : Starting new HTTPS connection (4): myorg.vsblob.visualstudio.com:443
msrest.exceptions : Error occurred in request., SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))
Failed to update Universal Packages tooling.
Error occurred in request., SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 342, in send
    response = http_driver.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 187, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool_updater.py", line 53, in _get_artifacttool
    release = self._get_current_release(team_instance, override_version)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool_updater.py", line 75, in _get_current_release
    release = client.get_clienttool_release("ArtifactTool", os_name=platform.system(), arch=platform.machine(), version=override_version)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\client_tool\client_tool_client.py", line 35, in get_clienttool_release
    query_parameters=query_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 71, in _send
    query_parameters=query_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 108, in _create_request_message
    location = self._get_resource_location(location_id)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 140, in _get_resource_location
    VssClient._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 176, in _get_resource_locations
    response = self._send_request(request, headers=headers)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 59, in _send_request
    content=content, **operation_config)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 369, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\exceptions.py", line 54, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 342, in send
    response = http_driver.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 187, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 203, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\universal.py", line 41, in publish_package
    return artifact_tool.publish_universal(team_instance, feed, name, version, description, path)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 30, in publish_universal
    return self.run_artifacttool(team_instance, args, "Publishing")
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 34, in run_artifacttool
    artifacttool_dir = self._artifacttool_updater.get_latest_artifacttool(team_instance)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool_updater.py", line 37, in get_latest_artifacttool
    artifacttool_binary_path = self._get_artifacttool(team_instance)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool_updater.py", line 55, in _get_artifacttool
    raise CLIError('Failed to update Universal Packages tooling.\n{}'.format(ex))
knack.util.CLIError: Failed to update Universal Packages tooling.
Error occurred in request., SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))
Failed to update Universal Packages tooling.
Error occurred in request., SSLError: HTTPSConnectionPool(host='myorg.vsblob.visualstudio.com', port=443): Max retries exceeded with url: /_apis (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)')))
PS D:\nuget_publish\appdynamics_universalpackage>
```

**Comment by snankani** [comment]
@ahaleiii 

Request to take a look at the response shared by zarenner and please feel free to reopen the issue if you see any further action from our end.
